spring:
  datasource:
    url :jdbc:h2:mem:localdb
    driverClassName:org.h2.Driver
    username:sa
    password:password
    database-platform:org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.data.rest.basePath=/api
